exclude:  ^tests/resources/ips/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: check-ipxml
    -   id: double-quote-string-fixer
    -   id: fix-encoding-pragma
    -   id: forbid-new-submodules
    -   id: name-tests-test
    -   id: trailing-whitespace
