# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[testing]"
    - name: Install python package
      run: |
        pip install --editable ".[testing]"
    - name: Static Pylint code QA
      run: |
        pylint --errors-only eark_validator
    - name: Run pre-commit tests
      run: pre-commit run --all-files --verbose
    - name: Test with pytest
      run: |
        pytest
    - name: Test setuptools-git-versioning versioning
      run: |
        python -m pip install setuptools_git_versioning
        python -m setuptools_git_versioning
    - name: Install build utils
      run: |
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
